//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GyCAP.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString3 {
            get {
                return ((string)(this["ProyectoConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString2 {
            get {
                return ((string)(this["ProyectoConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString1 {
            get {
                return ((string)(this["ProyectoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString4 {
            get {
                return ((string)(this["ProyectoConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString5 {
            get {
                return ((string)(this["ProyectoConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString7 {
            get {
                return ((string)(this["ProyectoConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Proyecto,2555;Initial Catalog=Proyecto;Persist Security Info=True;Use" +
            "r ID=sa;Password=spg2010")]
        public string ProyectoConnectionString {
            get {
                return ((string)(this["ProyectoConnectionString"]));
            }
        }
    }
}
